### ISSUE TITLE
Creacion de Tabla "Tipo"

### ISSUE THREAD

**Issue by guelo2019** [WayarCarla/PROYECTO-INTEGRADOR#12]
Crear tabla de referencia de acuerdo a la consigna del TP

**Comment by dr-arriola** [comment]
CREATE TABLE IF NOT EXISTS `db_inm_brf`.`tipo` (
  `Id_Tipo` INT NOT NULL,
  `Nombre_Tipo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Id_Tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla Tipo de Propiedad';
