### ISSUE TITLE
Generar Clase de la Tabla Propietario

### ISSUE THREAD

**Issue by OscarAGazzola** [WayarCarla/PROYECTO-INTEGRADOR#38]
Generar clase Propietario

**Comment by guelo2019** [comment]
class Propietario:
    
    Id_Propietario =""
    Nombre =""
    Apellido =""
    Direccion =""
    Telefono =""
    Email =""
    
    
    def __init__(self, Id_Propietario, Nombre, Apellido ,Direccion, Telefono, Email):
        self.Id_Propietario = Id_Propietario,
        self.Nombre = Nombre,
        self.Apellido = Apellido,
        self.Direccion = Direccion,
        self.Telefono = Telefono,
        self.Email = Email,
                
    def get_Id_Propietario(self):
        return Id_Propietario    

    def set_Id_Propietario(self,Id_Propietario):
        self.Id_Propietario= Id_Propietario
        
    def get_Nombre(self):
        return Nombre
    
    def set_Nombre(self,Nombre):
        self.Nombre= Nombre
        
    def get_Apellido(self):
        return Apellido

    def set_Apellido(self, Apellido):
        self.Apellido = Apellido

    def get_Direccion(self):
        return Direccion

    def set_Direccion(self, Direccion):
        self.Direccion = Direccion

    def get_Telefono(self):
        return Telefono

    def set_Telefono(self, Telefono):
        self.Telefono = Telefono
        
    def get_Email(self):
        return Email

    def set_Email(self, Email):
        self.Email = Email
