### ISSUE TITLE
Generar la Clase de la Tabla OperatoriaComercial

### ISSUE THREAD

**Issue by OscarAGazzola** [WayarCarla/PROYECTO-INTEGRADOR#41]
Generar la Clase

**Comment by guelo2019** [comment]
se genero Tabla

CREATE TABLE IF NOT EXISTS `db_inm_brf`.`operatoria comercial` (
  `Id_Operatoria_Comercial` INT NOT NULL,
  `Nombre_Operatoria_Comercial` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Id_Operatoria_Comercial`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla de Operatoria Comercial';
